importing

In [2]:
import numpy as np 

In [3]:
#set precision
np.set_printoptions(precision=2)

creating matrix

In [5]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [6]:
b = np.array([[1,2,3],[4,5,6]])
print (b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [7]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(b.shape)
print(b.ndim)


[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3)
2


- generate matrix 
  - linear
      - 
  - random

In [9]:
np.arange(1,100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [11]:
a = np.arange(1, 10 , .25)
print(a)
a.size

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


36

In [12]:
b = np.linspace (1, 10, 100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [14]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [15]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [17]:
np.random.rand(3,3)

array([[0.6 , 0.12, 0.29],
       [0.57, 0.38, 0.67],
       [0.88, 0.11, 0.42]])

In [18]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [22]:
print(np.random.randn(5,5))

[[-1.93  0.34  1.45 -0.94 -0.82]
 [-0.05  0.81 -0.34 -0.52  0.18]
 [ 0.    0.89 -1.4   1.1  -0.33]
 [ 0.17  0.18  0.23 -0.5   1.17]
 [ 0.31 -1.71  0.04  0.34 -1.17]]


In [20]:
print(np.random.randint(1, 100, (5,8)))

[[50 54 22 98 88 88  2 65]
 [74 76  9 15 31 74 98 49]
 [97 21  9 34 73 86  9 84]
 [ 8 96 57 81 93 55 95 49]
 [27  3 60 59 43 17 26 92]]


In [27]:
x = np.random.randint(1,11,(3,3))
y = np.random.randint(1,11,(3,3))
print(x)
print(y)

[[ 2  3 10]
 [ 1  2 10]
 [ 3  6  2]]
[[ 8  2  6]
 [ 8 10  5]
 [ 5  2  6]]


In [28]:
x + y #element wise addiction

array([[10,  5, 16],
       [ 9, 12, 15],
       [ 8,  8,  8]])

In [29]:
x - 10

array([[-8, -7,  0],
       [-9, -8,  0],
       [-7, -4, -8]])

In [30]:
x.dot(y)

array([[90, 54, 87],
       [74, 42, 76],
       [82, 70, 60]])