importing

In [1]:
import numpy as np 

In [2]:
#set precision
np.set_printoptions(precision=2)

creating matrix

In [3]:
a = np.array([2,5,6])
print(a)
print(a.shape)
print(a.dtype)

[2 5 6]
(3,)
int32


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print (b)
print(b.shape)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [5]:
c = np.array([[[1,2],[2,3],[3,1]],[[1,2],[3,1],[3,4]]])
print(c)
print(b.shape)
print(b.ndim)


[[[1 2]
  [2 3]
  [3 1]]

 [[1 2]
  [3 1]
  [3 4]]]
(2, 3)
2


- generate matrix 
  - linear
      
  - random

In [6]:
np.arange(1,100, 5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [7]:
a = np.arange(1, 10 , .25)
print(a)
a.size

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


36

In [8]:
b = np.linspace (1, 10, 100)
print(b)

[ 1.    1.09  1.18  1.27  1.36  1.45  1.55  1.64  1.73  1.82  1.91  2.
  2.09  2.18  2.27  2.36  2.45  2.55  2.64  2.73  2.82  2.91  3.    3.09
  3.18  3.27  3.36  3.45  3.55  3.64  3.73  3.82  3.91  4.    4.09  4.18
  4.27  4.36  4.45  4.55  4.64  4.73  4.82  4.91  5.    5.09  5.18  5.27
  5.36  5.45  5.55  5.64  5.73  5.82  5.91  6.    6.09  6.18  6.27  6.36
  6.45  6.55  6.64  6.73  6.82  6.91  7.    7.09  7.18  7.27  7.36  7.45
  7.55  7.64  7.73  7.82  7.91  8.    8.09  8.18  8.27  8.36  8.45  8.55
  8.64  8.73  8.82  8.91  9.    9.09  9.18  9.27  9.36  9.45  9.55  9.64
  9.73  9.82  9.91 10.  ]


In [9]:
b.reshape(25,4)

array([[ 1.  ,  1.09,  1.18,  1.27],
       [ 1.36,  1.45,  1.55,  1.64],
       [ 1.73,  1.82,  1.91,  2.  ],
       [ 2.09,  2.18,  2.27,  2.36],
       [ 2.45,  2.55,  2.64,  2.73],
       [ 2.82,  2.91,  3.  ,  3.09],
       [ 3.18,  3.27,  3.36,  3.45],
       [ 3.55,  3.64,  3.73,  3.82],
       [ 3.91,  4.  ,  4.09,  4.18],
       [ 4.27,  4.36,  4.45,  4.55],
       [ 4.64,  4.73,  4.82,  4.91],
       [ 5.  ,  5.09,  5.18,  5.27],
       [ 5.36,  5.45,  5.55,  5.64],
       [ 5.73,  5.82,  5.91,  6.  ],
       [ 6.09,  6.18,  6.27,  6.36],
       [ 6.45,  6.55,  6.64,  6.73],
       [ 6.82,  6.91,  7.  ,  7.09],
       [ 7.18,  7.27,  7.36,  7.45],
       [ 7.55,  7.64,  7.73,  7.82],
       [ 7.91,  8.  ,  8.09,  8.18],
       [ 8.27,  8.36,  8.45,  8.55],
       [ 8.64,  8.73,  8.82,  8.91],
       [ 9.  ,  9.09,  9.18,  9.27],
       [ 9.36,  9.45,  9.55,  9.64],
       [ 9.73,  9.82,  9.91, 10.  ]])

In [10]:
b.reshape(5,5,4)

array([[[ 1.  ,  1.09,  1.18,  1.27],
        [ 1.36,  1.45,  1.55,  1.64],
        [ 1.73,  1.82,  1.91,  2.  ],
        [ 2.09,  2.18,  2.27,  2.36],
        [ 2.45,  2.55,  2.64,  2.73]],

       [[ 2.82,  2.91,  3.  ,  3.09],
        [ 3.18,  3.27,  3.36,  3.45],
        [ 3.55,  3.64,  3.73,  3.82],
        [ 3.91,  4.  ,  4.09,  4.18],
        [ 4.27,  4.36,  4.45,  4.55]],

       [[ 4.64,  4.73,  4.82,  4.91],
        [ 5.  ,  5.09,  5.18,  5.27],
        [ 5.36,  5.45,  5.55,  5.64],
        [ 5.73,  5.82,  5.91,  6.  ],
        [ 6.09,  6.18,  6.27,  6.36]],

       [[ 6.45,  6.55,  6.64,  6.73],
        [ 6.82,  6.91,  7.  ,  7.09],
        [ 7.18,  7.27,  7.36,  7.45],
        [ 7.55,  7.64,  7.73,  7.82],
        [ 7.91,  8.  ,  8.09,  8.18]],

       [[ 8.27,  8.36,  8.45,  8.55],
        [ 8.64,  8.73,  8.82,  8.91],
        [ 9.  ,  9.09,  9.18,  9.27],
        [ 9.36,  9.45,  9.55,  9.64],
        [ 9.73,  9.82,  9.91, 10.  ]]])

In [33]:
np.random.rand(4,4)

array([[0.86, 0.84, 0.09, 0.76],
       [0.98, 0.03, 0.09, 0.89],
       [0.34, 0.14, 0.06, 0.91],
       [0.37, 0.31, 0.47, 0.08]])

In [12]:
np.random.randn?

Docstring:
randn(d0, d1, ..., dn)

Return a sample (or samples) from the "standard normal" distribution.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `standard_normal`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

.. note::
    New code should use the
    `~numpy.random.Generator.standard_normal`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

If positive int_like arguments are provided, `randn` generates an array
of shape ``(d0, d1, ..., dn)``, filled
with random floats sampled from a univariate "normal" (Gaussian)
distribution of mean 0 and variance 1. A single float randomly sampled
from the distribution is returned if no argument is provided.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    I

In [13]:
print(np.random.randn(5,5))

[[ 1.69  0.33  0.92  1.28 -0.84]
 [ 1.75  1.59 -1.66 -0.35 -0.83]
 [ 0.89  0.93 -1.69  1.22 -0.62]
 [ 1.94  1.7   0.29  0.2   0.98]
 [ 1.16  0.61 -0.36  1.59 -1.26]]


In [14]:
print(np.random.randint(1, 100, (5,8)))

[[19 25 82 11 37 31 78  5]
 [18 41 78 21 98 62 89 44]
 [31 47 84 66 20 83 43 35]
 [11 90 34 16 48 86 11 54]
 [19 56  7 18  4 25 75 22]]


In [15]:
x = np.random.randint(1,11,(3,3))
y = np.random.randint(1,11,(3,3))
print(x)
print(y)

[[ 1  9  9]
 [ 9  1  9]
 [10  9  3]]
[[ 6  7 10]
 [ 6  7  2]
 [ 2  4  5]]


In [16]:
x + y #element wise addiction

array([[ 7, 16, 19],
       [15,  8, 11],
       [12, 13,  8]])

In [17]:
x - 10

array([[-9, -1, -1],
       [-1, -9, -1],
       [ 0, -1, -7]])

In [18]:
x.dot(y)

array([[ 78, 106,  73],
       [ 78, 106, 137],
       [120, 145, 133]])

In [19]:
np.diag([1,2,2,4])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 4]])

21 August 

In [20]:
x = np.random.randint(20, 50, (6,6))
print(x)

[[21 32 30 32 30 35]
 [45 20 27 24 30 20]
 [24 36 42 41 40 27]
 [26 24 26 26 31 27]
 [22 42 23 44 40 45]
 [43 47 40 38 46 41]]


In [21]:
z = []
for i in x:
    for j in i :
        if j > 30:
            z.append(j)
print(np.array(z))
#this is not the best way             

[32 32 35 45 36 42 41 40 31 42 44 40 45 43 47 40 38 46 41]


In [22]:
x > 30 #filter

array([[False,  True, False,  True, False,  True],
       [ True, False, False, False, False, False],
       [False,  True,  True,  True,  True, False],
       [False, False, False, False,  True, False],
       [False,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [23]:
print(x[x>30])  #boolean filtering 

[32 32 35 45 36 42 41 40 31 42 44 40 45 43 47 40 38 46 41]


In [24]:
f = x < 40 #write filter in variable 
x[f] 

array([21, 32, 30, 32, 30, 35, 20, 27, 24, 30, 20, 24, 36, 27, 26, 24, 26,
       26, 31, 27, 22, 23, 38])

In [25]:
x[(x>30) & (x<45)]

array([32, 32, 35, 36, 42, 41, 40, 31, 42, 44, 40, 43, 40, 38, 41])

In [26]:
f1 = x >30
f2 = x < 45
x[f1 & f2]

array([32, 32, 35, 36, 42, 41, 40, 31, 42, 44, 40, 43, 40, 38, 41])

slicing 
1D = `[START : STOP : STEP]`

2D  = [r_start : r_stop : r_step : c_start : c_stop : c_step]

In [27]:
print('first row' )
print(x[0])

first row
[21 32 30 32 30 35]


In [28]:
print('last row')
print(x[-1])

last row
[43 47 40 38 46 41]


In [29]:
print('slice 2 to 5')
print(x[2:6])

slice 2 to 5
[[24 36 42 41 40 27]
 [26 24 26 26 31 27]
 [22 42 23 44 40 45]
 [43 47 40 38 46 41]]


In [30]:
x [:,0]

array([21, 45, 24, 26, 22, 43])

In [31]:
x[:,:3] #select first 3 columns

array([[21, 32, 30],
       [45, 20, 27],
       [24, 36, 42],
       [26, 24, 26],
       [22, 42, 23],
       [43, 47, 40]])

In [32]:
x[:,:-3] #select last 3 columns

array([[21, 32, 30],
       [45, 20, 27],
       [24, 36, 42],
       [26, 24, 26],
       [22, 42, 23],
       [43, 47, 40]])